<a href="https://colab.research.google.com/github/haseeb1zahid/Machine-Learning-Projects/blob/master/IrisClassificationKNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np  
import matplotlib.pyplot as plt  
import pandas as pd

In [0]:
from sklearn.datasets import load_iris

irisData = load_iris()

In [0]:
x = irisData.data
y = irisData.target

In [12]:
print(x[0])

[5.1 3.5 1.4 0.2]


In [14]:
print(y[0])

0


In [0]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()  
scaler.fit(x)
x = scaler.transform(x)  

In [0]:
# dummy_y = np_utils.to_categorical(encoded_Y)

In [0]:
from sklearn.model_selection import train_test_split  

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.30)

In [24]:
from sklearn.neighbors import KNeighborsClassifier  
classifier = KNeighborsClassifier(n_neighbors=5)  
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)  

from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

[[18  0  0]
 [ 0 15  1]
 [ 0  1 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       0.94      0.94      0.94        16
           2       0.91      0.91      0.91        11

   micro avg       0.96      0.96      0.96        45
   macro avg       0.95      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45



In [30]:
from sklearn.neighbors import KNeighborsClassifier  
classifier = KNeighborsClassifier(n_neighbors=3)  
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)  

from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

[[18  0  0]
 [ 0 14  2]
 [ 0  2  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        18
           1       0.88      0.88      0.88        16
           2       0.82      0.82      0.82        11

   micro avg       0.91      0.91      0.91        45
   macro avg       0.90      0.90      0.90        45
weighted avg       0.91      0.91      0.91        45

